//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheduleHelper.Core.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SheduleHelper.Core.Resources.Strings.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Timeline.
        /// </summary>
        public static string daily_timeline_header {
            get {
                return ResourceManager.GetString("daily_timeline_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested arrival time for one-click clock-in..
        /// </summary>
        public static string settings_defaultClockIn_description {
            get {
                return ResourceManager.GetString("settings_defaultClockIn_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default clock-in time.
        /// </summary>
        public static string settings_defaultClockIn_header {
            get {
                return ResourceManager.GetString("settings_defaultClockIn_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested departure time for one-click clock-out..
        /// </summary>
        public static string settings_defaultClockOut_description {
            get {
                return ResourceManager.GetString("settings_defaultClockOut_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default clock-out time.
        /// </summary>
        public static string settings_defaultClockOut_header {
            get {
                return ResourceManager.GetString("settings_defaultClockOut_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string settings_discard_button {
            get {
                return ResourceManager.GetString("settings_discard_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the app&apos;s display language..
        /// </summary>
        public static string settings_language_description {
            get {
                return ResourceManager.GetString("settings_language_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string settings_language_header {
            get {
                return ResourceManager.GetString("settings_language_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes deducted once you&apos;ve been clocked in past the threshold..
        /// </summary>
        public static string settings_lunchDuration_description {
            get {
                return ResourceManager.GetString("settings_lunchDuration_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch duration.
        /// </summary>
        public static string settings_lunchDuration_header {
            get {
                return ResourceManager.GetString("settings_lunchDuration_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the app deducts your lunch break from attendance time..
        /// </summary>
        public static string settings_lunchStrategy_description {
            get {
                return ResourceManager.GetString("settings_lunchStrategy_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch break rule.
        /// </summary>
        public static string settings_lunchStrategy_header {
            get {
                return ResourceManager.GetString("settings_lunchStrategy_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of the fixed lunch window to deduct..
        /// </summary>
        public static string settings_lunchWindowEnd_description {
            get {
                return ResourceManager.GetString("settings_lunchWindowEnd_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch window end.
        /// </summary>
        public static string settings_lunchWindowEnd_header {
            get {
                return ResourceManager.GetString("settings_lunchWindowEnd_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of the fixed lunch window to deduct..
        /// </summary>
        public static string settings_lunchWindowStart_description {
            get {
                return ResourceManager.GetString("settings_lunchWindowStart_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch window start.
        /// </summary>
        public static string settings_lunchWindowStart_header {
            get {
                return ResourceManager.GetString("settings_lunchWindowStart_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure your shift target, default clock times, and lunch break rules..
        /// </summary>
        public static string settings_page_subtitle {
            get {
                return ResourceManager.GetString("settings_page_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings_page_title {
            get {
                return ResourceManager.GetString("settings_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string settings_save_button {
            get {
                return ResourceManager.GetString("settings_save_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many hours count as a full workday..
        /// </summary>
        public static string settings_targetShiftHours_description {
            get {
                return ResourceManager.GetString("settings_targetShiftHours_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target shift hours.
        /// </summary>
        public static string settings_targetShiftHours_header {
            get {
                return ResourceManager.GetString("settings_targetShiftHours_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the app&apos;s visual theme..
        /// </summary>
        public static string settings_theme_description {
            get {
                return ResourceManager.GetString("settings_theme_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string settings_theme_header {
            get {
                return ResourceManager.GetString("settings_theme_header", resourceCulture);
            }
        }
    }
}
