//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheduleHelper.Core.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SheduleHelper.Core.Resources.Strings.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already clocked in for today..
        /// </summary>
        public static string error_alreadyClockedInToday {
            get {
                return ResourceManager.GetString("error_alreadyClockedInToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock-in time can&apos;t be in the future..
        /// </summary>
        public static string error_clockInTimeInFuture {
            get {
                return ResourceManager.GetString("error_clockInTimeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while clocking in. Please try again..
        /// </summary>
        public static string error_clockInUnexpected {
            get {
                return ResourceManager.GetString("error_clockInUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock-out time must be after your clock-in time..
        /// </summary>
        public static string error_clockOutBeforeClockIn {
            get {
                return ResourceManager.GetString("error_clockOutBeforeClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock-out time can&apos;t be in the future..
        /// </summary>
        public static string error_clockOutTimeInFuture {
            get {
                return ResourceManager.GetString("error_clockOutTimeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while clocking out. Please try again..
        /// </summary>
        public static string error_clockOutUnexpected {
            get {
                return ResourceManager.GetString("error_clockOutUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while loading your dashboard. Please try again..
        /// </summary>
        public static string error_homeLoadUnexpected {
            get {
                return ResourceManager.GetString("error_homeLoadUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not currently clocked in..
        /// </summary>
        public static string error_notClockedIn {
            get {
                return ResourceManager.GetString("error_notClockedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for the project..
        /// </summary>
        public static string error_projectNameEmpty {
            get {
                return ResourceManager.GetString("error_projectNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving your project. Please try again..
        /// </summary>
        public static string error_projectSaveUnexpected {
            get {
                return ResourceManager.GetString("error_projectSaveUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while loading your settings. Please try again..
        /// </summary>
        public static string error_settingsLoadUnexpected {
            get {
                return ResourceManager.GetString("error_settingsLoadUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving your settings. Please try again..
        /// </summary>
        public static string error_settingsSaveUnexpected {
            get {
                return ResourceManager.GetString("error_settingsSaveUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while saving your task. Please try again..
        /// </summary>
        public static string error_taskSaveUnexpected {
            get {
                return ResourceManager.GetString("error_taskSaveUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title for the task..
        /// </summary>
        public static string error_taskTitleEmpty {
            get {
                return ResourceManager.GetString("error_taskTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not currently tracking a project..
        /// </summary>
        public static string error_trackingNotActive {
            get {
                return ResourceManager.GetString("error_trackingNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start tracking in the future..
        /// </summary>
        public static string error_trackingStartTimeInFuture {
            get {
                return ResourceManager.GetString("error_trackingStartTimeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while switching projects. Please try again..
        /// </summary>
        public static string error_trackingUnexpected {
            get {
                return ResourceManager.GetString("error_trackingUnexpected", resourceCulture);
            }
        }
    }
}
