// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stint.Core;

#nullable disable

namespace Stint.Core.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Stint.Core.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("ClockIn")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClockIn");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClockOut");

                    b.Property<TimeSpan?>("CreditedDuration")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreditedDuration");

                    b.Property<int>("DayType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DayType");

                    b.Property<string>("WorkDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkDate");

                    b.HasKey("Id");

                    b.HasIndex("WorkDate")
                        .IsUnique();

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("Stint.Core.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Stint.Core.ProjectTimeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AttendanceLogId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AttendanceLogId");

                    b.Property<int?>("ClosedReason")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ClosedReason");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndTime");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProjectId");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartTime");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TaskId");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceLogId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId");

                    b.ToTable("ProjectTimeLogs");
                });

            modelBuilder.Entity("Stint.Core.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProjectId");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Stint.Core.ProjectTimeLog", b =>
                {
                    b.HasOne("Stint.Core.AttendanceLog", "AttendanceLog")
                        .WithMany("ProjectTimeLogs")
                        .HasForeignKey("AttendanceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stint.Core.Project", "Project")
                        .WithMany("ProjectTimeLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stint.Core.TaskItem", "Task")
                        .WithMany("ProjectTimeLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AttendanceLog");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Stint.Core.TaskItem", b =>
                {
                    b.HasOne("Stint.Core.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Stint.Core.AttendanceLog", b =>
                {
                    b.Navigation("ProjectTimeLogs");
                });

            modelBuilder.Entity("Stint.Core.Project", b =>
                {
                    b.Navigation("ProjectTimeLogs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Stint.Core.TaskItem", b =>
                {
                    b.Navigation("ProjectTimeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
