// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SheduleHelper.Core.Models;

#nullable disable

namespace SheduleHelper.Core.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("ClockIn")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClockIn");

                    b.Property<DateTime?>("ClockOut")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClockOut");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<string>("WorkDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("WorkDate");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WorkDate")
                        .IsUnique();

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.ProjectTimeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<int>("AttendanceLogId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AttendanceLogId");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("EndTime");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProjectId");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("StartTime");

                    b.Property<int?>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TaskId");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceLogId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId");

                    b.ToTable("ProjectTimeLogs");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ProjectId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.UserSetting", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<TimeOnly>("DefaultClockInTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DefaultClockInTime");

                    b.Property<TimeOnly>("DefaultClockOutTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("DefaultClockOutTime");

                    b.Property<int>("LunchDurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LunchDurationMinutes");

                    b.Property<TimeOnly>("LunchEndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LunchEndTime");

                    b.Property<TimeOnly>("LunchStartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LunchStartTime");

                    b.Property<string>("LunchStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LunchStrategy");

                    b.Property<decimal>("TargetShiftHours")
                        .HasColumnType("TEXT")
                        .HasColumnName("TargetShiftHours");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.AttendanceLog", b =>
                {
                    b.HasOne("SheduleHelper.Core.Components.Entities.User", "User")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.Project", b =>
                {
                    b.HasOne("SheduleHelper.Core.Components.Entities.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.ProjectTimeLog", b =>
                {
                    b.HasOne("SheduleHelper.Core.Components.Entities.AttendanceLog", "AttendanceLog")
                        .WithMany("ProjectTimeLogs")
                        .HasForeignKey("AttendanceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheduleHelper.Core.Components.Entities.Project", "Project")
                        .WithMany("ProjectTimeLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SheduleHelper.Core.Components.Entities.TaskItem", "Task")
                        .WithMany("ProjectTimeLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AttendanceLog");

                    b.Navigation("Project");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.TaskItem", b =>
                {
                    b.HasOne("SheduleHelper.Core.Components.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.UserSetting", b =>
                {
                    b.HasOne("SheduleHelper.Core.Components.Entities.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("SheduleHelper.Core.Components.Entities.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.AttendanceLog", b =>
                {
                    b.Navigation("ProjectTimeLogs");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.Project", b =>
                {
                    b.Navigation("ProjectTimeLogs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.TaskItem", b =>
                {
                    b.Navigation("ProjectTimeLogs");
                });

            modelBuilder.Entity("SheduleHelper.Core.Components.Entities.User", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("Projects");

                    b.Navigation("UserSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
